import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import SkillsSelection from '@/components/skills-selection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.leftColumn}>
          <h2 className={inter.className}>Skills Selection</h2>
          <SkillsSelection />
        </div>
        <div className={styles.rightColumn}>

        </div>
      </main>
    </>
  )
}
